name: test-failure
on:
  push:
jobs:
  successed-job:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  failed-job:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  assert-workflow-status:
    if: always()
    runs-on: ubuntu-latest
    needs:
      - successed-job
      - failed-job
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - id: workflow-status
        uses: ./
      - run: test ${{ steps.workflow-status.outputs.status }} = "failure"
