name: test-timeout
on:
  push:
jobs:
  successed-job:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  timeout-job:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - run: sleep 61
  assert-workflow-status:
    if: always()
    runs-on: ubuntu-latest
    needs:
      - successed-job
      - timeout-job
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - id: workflow-status
        uses: ./
      - run: test ${{ steps.workflow-status.outputs.status }} = "cancelled"
