name: test-success
on:
  push:
jobs:
  successed-job-1:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  successed-job-2:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  assert-workflow-status:
    if: always()
    runs-on: ubuntu-latest
    needs:
      - successed-job-1
      - successed-job-2
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - id: workflow-status
        uses: ./
      - run: test ${{ steps.workflow-status.outputs.status }} = "success"
